# Default values for openam-install.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

# Default values for openam-dev.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into the templates

image: forgerock/openam
imageTag: latest

# Server base URL *within* the k8s cluster - not the external LB URL
# No /openam appended here.
serverBase: http://openam:80

# What OpenAM is known by *outside* the cluster - includes context root /openam
#loadBalancerUrl: "https://openam.test.com:443/openam"
loadBalancerUrl: "http://openam.test.com:80/openam"


fqdnHostname: openam.test.com
cookieDomain: .test.com
amadmin_pw: password


# Suffix for OpenDJ config store
rootSuffix:  "dc=openam,dc=forgerock,dc=org"

# Hostname of opendj config store within the k8s cluster
# This is the name of the first instance in the petset
djConfigHost: opendj-configstore-0.opendj-configstore


# Image for OpenAM configurator
configImage: forgerock/openam-config
configImageTag: latest