# Experimental use of ConfigMap
# Concept: Dynamically configure AM based on configuration template
# The values here get substitued into the AM template that ssoconfig uses
kind: ConfigMap
apiVersion: v1
metadata:
  name: am-config
  namespace: default
data:
#  openam.fqdn:  http://openam.example.com:80/openam
#  openam.cookiedomain: .example.
  openam.fqdn:  https://test.my2do.com:443/openam
  openam.cookiedomain: .my2do.com
  openam.configurl: https://raw.githubusercontent.com/ForgeRock/fretes/master/config/openam/01_config.properties
